Enhancing the vote commands
NamelessGroup/namelessbot pull request #115
Opened 2023-08-02 11:49 UTC by ProgramPhoenix

Following enhancements are included in this PR:

1. The Bot does not crashes anymore if its called in a channel it has no access to
2. majority votes need now the majority on one side
3. offline members will also calculated in the required votes on a majority vote

2023-08-02 14:45 UTC, ProgramPhoenix commented
short note: this pr leads to the need of the priviledged gateway intent: server members intent (so we can fetch the offline members

2023-09-07 15:23 UTC, c0derMo requested changes

2023-09-07 15:23 UTC, c0derMo commented on modules/vote/voteCommand.ts
> +            msg += "This is a majority voting. " + usedVotes + " Votes are on one position required!";
I feel like "position" is weirdly worded here

2023-10-27 07:02 UTC, c0derMo approved these changes

2023-10-27 07:02 UTC, merged