Improve documentation
NamelessGroup/namelessbot pull request #66
Opened 2023-02-07 13:15 UTC by c0derMo

Closes #25.

This PR aims to improve code quality by adding more linting rules, aswell as enforcing jsdoc comments.

This PR also adds automatic documentation builds & publishes them to https://namelessgroup.github.io/namelessbot
The published version only updates when triggered manually or at pushes to master.

Reviews from all three contributors (@c0derMo, @Kr0nox, @MartinKrausewitz) should be awaited before merging this request.

2023-02-07 14:19 UTC, MartinKrausewitz approved these changes
Seems pretty good. We need to force @myphyk to implement the wednesday recurring message ;D

2023-02-07 16:09 UTC, Kr0nox requested changes

2023-02-07 16:09 UTC, Kr0nox commented on lib/truthtable.ts
> + * Generates a truthtable with the supplied AST & variables
Should we use abbreviations that may not be known to all developers like ast? or should we use the written out from?

2023-02-07 16:09 UTC, Kr0nox commented on slashCommands/aoc.ts
> + * Slash command definition for /aoc, a command that sends the current leaderboard
All Slash-Command-Docs have the same structure except timetable (Wirrten like it is here). Should we make that uniform.

2023-02-07 16:09 UTC, Kr0nox commented on tasks/aoc.ts
> + * TaskExecutor that sends the current standings for the AoC competition.
Should we also make the documentation here uniform with the others in their wording at the start?

2023-02-07 16:25 UTC, Kr0nox commented
And @c0derMo we dscussed having the README on the first page of the docs. Is that possible?

2023-02-07 17:29 UTC, c0derMo commented
> And @c0derMo we dscussed having the README on the first page of the docs. Is that possible?

Should already be the case - the currently deployed version of the docs is *not* up to date. To look at the result, build them locally using `yarn doc`

2023-02-07 20:46 UTC, c0derMo commented
Also, we could concider getting rid of "messageCommands", since we don't use them since the introduction of slash commands

2023-02-08 09:18 UTC, c0derMo commented
Another question would be, if we want to enforce the usage of "full sentences" in description `@param` and '@returns` tags - "full sentences" being classified as ones starting with uppercase letters, ending in period, question mark, exclamation mark, etc.
@Kr0nox @MartinKrausewitz

2023-02-08 09:36 UTC, Kr0nox commented
Removing is is definitely the right way to go. Would it be better to remove it in this PR or when restructuring the entire code into modules?

2023-02-08 09:42 UTC, c0derMo reviewed
lgtm - apart from the open question about "chatCommands" (commands using messages starting with `!`)

2023-02-08 09:43 UTC, c0derMo commented
> Removing is is definitely the right way to go. Would it be better to remove it in this PR or when restructuring the entire code into modules?

@Kr0nox - I think we can also do this in the upcoming PR about restructuring, you're right
In which case, only your review is left until we can merge this ;)

2023-02-08 09:44 UTC, Kr0nox approved these changes
Everything lgtm

2023-02-08 10:42 UTC, merged